apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-url
  namespace: sock-shop
type: Opaque
data:
  slack-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA0QjVMS1AzSFQvQjA3R1A2U0pFUFEvRlNjYTF1VDJ5NjRqRnl5TGM1eE5DS01G
