apiVersion: cert-manager.io/v1 # test: cert-manager.io/v1alpha2 prod: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production-cluster
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory # test: https://acme-staging-v02.api.letsencrypt.org/directory prod: https://acme-v02.api.letsencrypt.org/directory
    email: azonubi.goodnews@gmail.com
    privateKeySecretRef:
      name: prod-issuer-secret
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: nginx
        # selector: {}
