alertmanager:
  alertmanagerSpec:
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ["job"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
        receiver: "slack-notifications"
      receivers:
        - name: "slack-notifications"
          slack_configs:
            - send_resolved: true
              channel: "#sock-shop-alerts'"
              api_url: "https://hooks.slack.com/services/your/webhook/url"
