name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure resources
        run: |
          az group create --name myResourceGroup --location eastus
          az deployment group create --resource-group myResourceGroup --template-file azuredeploy.json
